---
- name: Set up whole personal working environment on Ubuntu
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    homedir: /home/gleb
    username: gleb
    ubuntu: xenial

  roles:
  - role: common

  - role: vim
  - role: zsh
  - role: docker
  - role: java

  - role: idea
  - role: pycharm

  - role: chrome
  - role: spotify
  
  - role: dropbox

  - role: matcha-theme
  - role: papirus-icons
