---
- name: Set up whole work working environment on Ubuntu
  hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    homedir: /home/gleb
    username: gleb
    ubuntu: xenial

  roles:
  - role: common
  - role: vim
  - role: zsh
  - role: chrome