---
# Role to install pycharm
 - name: Check if pycharm is installed
   find: paths="{{ homedir }}/Programs" patterns="pycharm*" file_type=directory
   register: dir

 - name: Make directory for programs
   when: dir.matched == 0
   become_user: "{{ username }}"
   file: path="{{ homedir }}/Programs" state=directory
 
 - name: Download pyCharm
   when: dir.matched == 0
   become_user: "{{ username }}"
   get_url: url=https://download.jetbrains.com/python/pycharm-community-2018.2.4.tar.gz dest="{{ homedir }}/Downloads/pycharm.tar.gz"
 
 - name: Install pyCharm
   when: dir.matched == 0
   become_user: "{{ username }}"
   unarchive: src="{{ homedir }}/Downloads/pycharm.tar.gz" dest="{{ homedir }}/Programs/"

 - name: Delete pycharm installer
   file: path="{{ homedir }}/Downloads/pycharm.tar.gz" state=absent

