---
# Role to install gcc and g++ with versions needed
 - name: Install gcc-4.8
   apt: name=gcc-4.8

 - name: Update alternatives gcc
   alternatives: name=gcc path=/usr/bin/gcc-4.8 link=/usr/bin/gcc

 - name: Install g++-4.8
   apt: name=g++-4.8
   
 - name: Update alternatives g++
   alternatives: name=g++ path=/usr/bin/g++-4.8 link=/usr/bin/g++

 - name: Install cmake
   apt: name=cmake
