---
# Role to install idea and configs
 - name: Check if idea is installed
   find: paths="{{ homedir }}/Programs" patterns="idea*" file_type=directory
   register: dir

 - name: Make directory for programs
   when: dir.matched == 0
   become_user: "{{ username }}"
   file: path="{{ homedir }}/Programs" state=directory
 
 - name: Download Idea
   when: dir.matched == 0
   become_user: "{{ username }}"
   get_url: url=https://download.jetbrains.com/idea/ideaIC-2018.2.5.tar.gz dest="{{ homedir }}/Downloads/idea.tar.gz"
 
 - name: Install Idea
   when: dir.matched == 0
   become_user: "{{ username }}"
   unarchive: src="{{ homedir }}/Downloads/idea.tar.gz" dest="{{ homedir }}/Programs/"

 - name: Delete idea installer
   file: path="{{ homedir }}/Downloads/idea.tar.gz" state=absent
