---
# Role to install idea and configs
 - name: Make directory for programs
   become_user: "{{ username }}"
   file: path="{{ homedir }}/Programs" state=directory
 
 - name: Download Idea
   become_user: "{{ username }}"
   get_url: url=https://download.jetbrains.com/idea/ideaIU-2017.1.2.tar.gz dest="{{ homedir }}/Downloads/ideaIU-2017.1.2.tar.gz"
   register: download_idea_res
 
 - name: Install Idea
   when: download_idea_res.changed
   become_user: "{{ username }}"
   unarchive: src="{{ homedir }}/Downloads/ideaIU-2017.1.2.tar.gz" dest="{{ homedir }}/Programs/"

 - name: Make directory for Idea configs
   become_user: "{{ username }}"
   file: path="{{ homedir }}//.IntelliJIdeaConfig/" state=directory
 
 - name: Link Idea configs 1/2
   become_user: "{{ username }}"
   file: src="{{ playbook_dir }}/roles/idea/resources/idea/options" dest="{{ homedir }}/.IntelliJIdeaConfig/options" state=link
 
 - name: Link Idea configs 2/2
   become_user: "{{ username }}"
   file: src="{{ playbook_dir }}/roles/idea/resources/idea/plugins" dest="{{ homedir }}/.IntelliJIdeaConfig/plugins" state=link