---
# Role to install idea and configs
 - name: Make directory for programs
   become_user: "{{ username }}"
   file: path="{{ homedir }}/Programs" state=directory
 
 - name: Download Idea
   become_user: "{{ username }}"
   get_url: url=https://download.jetbrains.com/idea/ideaIC-2018.1.6.tar.gz dest="{{ homedir }}/Downloads/ideaIC-2018.1.6.tar.gz"
   register: download_idea_res
 
 - name: Install Idea
   when: download_idea_res.changed
   become_user: "{{ username }}"
   unarchive: src="{{ homedir }}/Downloads/ideaIC-2018.1.6.tar.gz" dest="{{ homedir }}/Programs/"
