---
# This role install basic packages for development
 - name: Install git
   apt: name=git state=latest
 - name: Install vim
   apt: name=vim state=latest

 - name: Install gcc-4.8
   apt: name=gcc-4.8 state=latest
 - name: gcc-4.8 as default gcc
   alternatives: name=gcc path=/usr/bin/gcc-4.8

 - name: Install g++-4.8
   apt: name=g++-4.8 state=latest
 - name: g++-4.8 as default g++
   alternatives: name=g++ path=/usr/bin/g++-4.8
