---
# This role install basic packages for development
 - name: Install git
   apt: name=git
 - name: Install vim
   apt: name=vim

 - name: Install gcc-4.8
   apt: name=gcc-4.8
 - name: Update alternatives gcc
   alternatives: name=gcc path=/usr/bin/gcc-4.8 link=/usr/bin/gcc

 - name: Install g++-4.8
   apt: name=g++-4.8
 - name: Update alternatives g++
   alternatives: name=g++ path=/usr/bin/g++-4.8 link=/usr/bin/g++

 - name: Add java repository
   apt_repository: repo=ppa:webupd8team/java
 - name: Agree with oracle license
   shell: "{{ playbook_dir }}/roles/dev_packages/scripts/oracle-licence.sh oracle-java8-installer" 
   changed_when: False
 - name: Install java 8
   apt: name=oracle-java8-installer
 - name: Set java defaults
   apt: name=oracle-java8-set-default
