---
# This role install basic packages for development
 - name: Install git
   apt: name=git

 - name: Install curl
   apt: name=curl

 - name: Install vim
   apt: name=vim
 - name: Create directory for vim colors
   file: path="{{homedir}}/.vim/colors/" state=directory
   become_user: "{{ username }}"
 - name: Install vim color scheme
   get_url: url=https://raw.githubusercontent.com/vim-scripts/256-jungle/master/colors/256-jungle.vim dest="{{ homedir }}/.vim/colors/256-jungle.vim"
   become_user: "{{ username }}"

 - name: Install gcc-4.8
   apt: name=gcc-4.8
 - name: Update alternatives gcc
   alternatives: name=gcc path=/usr/bin/gcc-4.8 link=/usr/bin/gcc

 - name: Install g++-4.8
   apt: name=g++-4.8
 - name: Update alternatives g++
   alternatives: name=g++ path=/usr/bin/g++-4.8 link=/usr/bin/g++

 - name: Install cmake
   apt: name=cmake

 - name: Add java repository
   apt_repository: repo=ppa:webupd8team/java
 - name: Agree with oracle license
   shell: "{{ playbook_dir }}/roles/dev_packages/scripts/oracle-licence.sh oracle-java8-installer" 
   register: oracle_license_res
   changed_when: "oracle_license_res.stdout == 'changed'"
 - name: Install java 8
   apt: name=oracle-java8-installer
 - name: Set java defaults
   apt: name=oracle-java8-set-default

 - name: Install maven
   apt: name=maven
 - name: Install gradle
   apt: name=gradle

 - name: Install postgresql
   apt: name=postgresql
   register: install_postgresql_res
 - name: Change psql authentification method
   shell: sed -i '/local   all             postgres/c\local   all             postgres                                trust' /etc/postgresql/9.5/main/pg_hba.conf
   changed_when: False
   when: install_postgresql_res.changed
 - name: Restart postgresql service
   systemd: name=postgresql enabled=yes state=restarted
   when: install_postgresql_res.changed

 - name: Install zsh
   apt: name=zsh
 - name: Install oh-my-zsh
   shell: "{{ playbook_dir }}/roles/dev_packages/scripts/install-oh-my-zsh.sh {{ homedir }} {{ username }}" 
   register: install_omz_res
   changed_when: "install_omz_res.stdout == 'changed'"
 - name: Install zsh-autosuggestion plugin
   git: clone=yes repo=https://github.com/zsh-users/zsh-autosuggestions.git dest="{{ homedir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions" update=no
   become_user: "{{ username }}"
 - name: Install zsh-syntax-highligting plugin  
   git: clone=yes repo=https://github.com/zsh-users/zsh-syntax-highlighting.git dest="{{ homedir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" update=no
   become_user: "{{ username }}"
 - name: Install Source Code Pro fonts
   copy: src="{{ playbook_dir }}/roles/dev_packages/resources/SourceCodeProFonts" dest="/usr/share/fonts"
 - name: Install powerline9k theme
   git: clone=yes repo=https://github.com/bhilburn/powerlevel9k.git dest="{{ homedir }}/.oh-my-zsh/custom/themes/powerlevel9k" update=no
   become_user: "{{ username }}"
 - name: Install docker deps 1/4
   apt: name=apt-transport-https
 - name: Install docker deps 2/4
   apt:  name=ca-certificates
 - name: Install docker deps 3/4
   apt: name=curl
 - name: Install docker deps 4/4
   apt: name=software-properties-common
 - name: Add docker PGP key
   apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
 - name: Add docker repository
   apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu }}  stable"
 - name: Install docker
   apt: name=docker-ce
 - name: Create docker group
   group: name=docker state=present system=yes
 - name: Add user to docker group
   user: name="{{ username }}" groups=docker append=yes
 - name: Enable docker to start on boot
   systemd: name=docker enabled=yes state=started
 - name: Install docker-compose
   get_url: url=https://github.com/docker/compose/releases/download/1.12.0/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose
 - name: Give execution permissions to binary
   file: path=/usr/local/bin/docker-compose mode=777
 - name: Create directory for zsh completions
   file: path="{{homedir}}/.oh-my-zsh/completion/" state=directory
   become_user: "{{ username }}"
 - name: Get docker-compose version
   shell: docker-compose version --short
   register: docker_compose_ver
   changed_when: False
 - name: Install docker-compose zsh autocompletion
   get_url: url="https://raw.githubusercontent.com/docker/compose/{{ docker_compose_ver.stdout }}/contrib/completion/zsh/_docker-compose" dest="{{ homedir }}/.oh-my-zsh/completion/_docker-compose"
   become_user: "{{ username }}"
 
 - name: Add google repository key
   apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
 - name: Add google repository
   apt_repository: repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
   register: add_google_repo_res
 - name: Update apt cache
   apt: update_cache=yes
   when: add_google_repo_res.changed
 - name: Install google chrome
   apt: name=google-chrome-stable

 - name: Make directory for programs
   file: path="{{ homedir }}/Programs" state=directory
   become_user: "{{ username }}"
 - name: Download Idea
   get_url: url=https://download.jetbrains.com/idea/ideaIU-2017.1.2.tar.gz dest="{{ homedir }}/Downloads/ideaIU-2017.1.2.tar.gz"
   register: download_idea_res
   become_user: "{{ username }}"
 - name: Install Idea
   unarchive: src="{{ homedir }}/Downloads/ideaIU-2017.1.2.tar.gz" dest="{{ homedir }}/Programs/"
   become_user: "{{ username }}"
   when: download_idea_res.changed
