---
# Role to install adapta unity theme
 - name: Add spotify repo key
   apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90 state=present

 - name: Add spotify repository
   apt_repository: repo="deb http://repository.spotify.com stable non-free"
   register: add_spotify_repo_yes

 - name: Update apt cache
   when: add_spotify_repo_yes.changed
   apt: update_cache=yes

 - name: Install spotify
   apt: name=spotify-client
        allow_unauthenticated=yes
