---
# This role makes links on all configs from resources to appropriate places
 - name: Delete old .gitconfig
   file: path="{{ homedir }}/.gitconfig" state=absent
 - name: Link .gitconfig
   file: src="{{ playbook_dir }}/roles/configs/resources/.gitconfig" dest="{{ homedir }}/.gitconfig" state=link

 - name: Delete old .vimrc
   file: path="{{ homedir }}/.vimrc" state=absent
 - name: Link .vimrc
   file: src="{{ playbook_dir }}/roles/configs/resources/.vimrc" dest="{{ homedir }}/.vimrc" state=link

 - name: Delete old .zshrc
   file: path="{{ homedir }}/.zshrc" state=absent
 - name: Link .zshrc
   file: src="{{ playbook_dir }}/roles/configs/resources/.zshrc" dest="{{ homedir }}/.zshrc" state=link

 - name: Make directory for Idea configs
   file: path="{{ homedir }}//.IntelliJIdeaConfig/" state=directory
 - name: Link Idea configs 1/2
   file: src="{{ playbook_dir }}/roles/configs/resources/idea/options" dest="{{ homedir }}/.IntelliJIdeaConfig/options" state=link
 - name: Link Idea configs 2/2
   file: src="{{ playbook_dir }}/roles/configs/resources/idea/plugins" dest="{{ homedir }}/.IntelliJIdeaConfig/plugins" state=link
