---
# Role to install google chrome
 - name: Add google repository key
   apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
 
 - name: Add google repository
   apt_repository: repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
   register: add_google_repo_res
 
 - name: Update apt cache
   when: add_google_repo_res.changed
   apt: update_cache=yes
 
 - name: Install google chrome
   apt: name=google-chrome-stable