---
# Role to install dropbox
 - name: Add dropbox repository key
   apt_key: keyserver=pgp.mit.edu id=1C61A2656FB57B7E4DE0F4C1FC918B335044912E

 - name: Add dropbox repository
   apt_repository: repo="deb http://linux.dropbox.com/ubuntu xenial main"

 - name: Install dropbox
   apt: name=dropbox
    
