---
# Role for common packages and configs
 - name: Add universe repo
   apt_repository: repo="deb http://archive.ubuntu.com/ubuntu bionic universe" state=present

 - name: Install gnome tweak tool
   apt: name=gnome-tweak-tool

 - name: Install curl
   apt: name=curl

 - name: Install git
   apt: name=git

 - name: Get stat of existing .gitconfig
   stat: path="{{ homedir }}/.gitconfig"
   register: gitconfig_stat
 
 - name: Backup existing .gitconfig
   when: (gitconfig_stat.stat.exists == True) and (gitconfig_stat.stat.islnk == False)
   become_user: "{{ username }}"
   copy: src="{{ homedir }}/.gitconfig" dest="{{ homedir }}/.gitconfig_old"
   register: backup_gitconfig_res
 
 - name: Delete existing .gitconfig
   when: backup_gitconfig_res.changed
   file: name="{{ homedir }}/.gitconfig" state=absent
 
 - name: Link .gitconfig
   become_user: "{{ username }}"
   file: src="{{ playbook_dir }}/roles/common/resources/.gitconfig" dest="{{ homedir }}/.gitconfig" state=link

 - name: Install python-dev package
   apt: name=python-dev

 - name: Install libboost-all-dev
   apt: name=libboost-all-dev

 - name: Install shutter
   apt: name=shutter

 - name: Install vlc
   apt: name=vlc
